### ISSUE TITLE
"received callback was unauthorized"

### ISSUE THREAD

**Issue by jontebotas** [scraton/node-red-contrib-telegrambot-home#1]
Hi! I am trying to use the switch-node, but won't get it to work. In my flow, I'm using an inject-node to post a dummy-message to the swtich-node. The outputs of the switch-node is then connected to an debug-node.

When clicking on the inject-node, the question and the two answers i have configured shows up in my telegram chat . But when I click on either answer in telegram, the debug-node shows the following output: 

msg : string[34]
"received callback was unauthorized"

Any idea of what can be wrong?
/Jonte

**Comment by scraton** [comment]
Hi there!

When you configured the bot, did you enter anything into the "Users" or "Chat IDs" field?

That error message will show when you get a response back, but the response is not from a user or chat defined in those fields. Do you have anything defined there? You can try clearing one or both of them and trying again. But if you need those fields, let me know what you've put into them and I can take a look at why it may not be working.

**Comment by jontebotas** [comment]
I did enter a user but no chat id in the bot configuration. I don't really need to limit the access to only my user, so will try to remove it from there and see how it goes! I'll keep you posted.

** EDIT ** I tested to remove my user from the chat bot and it now works like a charm! Thanks!

**Comment by scraton** [comment]
Great! Glad to hear you got it sorted.

FWIW I just pushed a new update that has enhanced logging to help troubleshoot this problem more in the future should it come up again. :)
