### ISSUE TITLE
In/out Json is not consistent

### ISSUE THREAD

**Issue by AlexJ777** [scraton/node-red-contrib-telegrambot-home#10]
Command returns ChatId at following path: msg.telegram.chat.id
Switch returns ChatID at following path: msg.telegram.chatId

Notify expects chatID at: msg.telegram.chat.id

So, if i have flow "command -> switch -> notify", i have to rebuild chat path myself, otherwise notify does not work.

Thsi should be made consistent by adding "chat.id" path to "notify" code.

**Comment by scraton** [comment]
Hi there! Thanks for reporting this and nice catch! I agree, it should be consistent so it's easier to combine the nodes together seamlessly.

I've fixed this in the latest update, 0.5.0, which should be available via the pallette manager soon. Try it out and let me know if it works out for you. :)

**Comment by AlexJ777** [comment]
Fix confirmed in 0.5.1. Sorry, i was too busy with real life.

**Comment by scraton** [comment]
It gets in the way sometimes doesn’t it? :P Thanks for confirming!
