### ISSUE TITLE
Command node without a Name property

### ISSUE THREAD

**Issue by xraysight** [scraton/node-red-contrib-telegrambot-home#11]
Thanks for the very useful telegram nodes! I have noticed Command misses "Name" property and therefore you cannot change its name (all nodes look the same on the flows page. Could you please add it the same way it is available in other nodes?

**Comment by scraton** [comment]
Hi there! Thanks for reporting this and good catch! This has been fixed in 0.5.1 which should be available via the palette manager shortly. :)
