### ISSUE TITLE
Received unauthorized message

### ISSUE THREAD

**Issue by albafer** [scraton/node-red-contrib-telegrambot-home#12]
Hi!!

Currently I'm using Notify node, but now, I would like to use the command node.

 I have tried with the same configuration but the console say me ""received unauthorized message in [CHAT ID] from [USER]".

I gave the permission to my bot and he has access to all messages. 

Do you have any idea to solve this?

Thank in you in advance!

**Comment by albafer** [comment]
Fix!!

It's was only a space in the users... you need to write user1,user2,user3,etc...

Thank you!!

**Comment by scraton** [comment]
Hi albafer! Thanks for mentioning the issue, it is a bit confusing since the chat IDs field does allow for spaces. I've fixed this up in 0.5.1 if you'd like to update. :)
