### ISSUE TITLE
Double notification

### ISSUE THREAD

**Issue by electricJP** [scraton/node-red-contrib-telegrambot-home#14]
Started very recently (a few days ago, not sure when), all "telegram notify" nodes will double send the message. In debug tab I can see nodes failing and retrying several times in a second:

17/10/2018 à 21:13:34node: f3376108.c9d9a
msg : string[26]
ETELEGRAM: 502 Bad Gateway

17/10/2018 à 21:13:34node: f3376108.c9d9a
msg : string[28]
"Unknown error. Trying again."

17/10/2018 à 21:13:34node: f3376108.c9d9a
msg : string[26]
"ETELEGRAM: 502 Bad Gateway"

17/10/2018 à 21:13:34node: f3376108.c9d9a
msg : string[28]
"Unknown error. Trying again."

The same setup was working perfectly a few days ago. I think some nodes got updated recently but not sure if telegrambot was. 

Running version 0.5.1 on node-red 0.19.4

**Comment by scraton** [comment]
Hello!

Thanks for reporting this. Are you still experiencing the issue? The 502 errors would seem to indicate a problem with Telegram's servers themselves, or something in between them and Node RED. I would suspect it should only be a temporal issue.

The retry mechanism is expected, though there probably should be some delay between the retries. Were there only 4 retries in your logs, or more than that? When I find some time I'll see about implementing a retry back off mechanism to avoid the log spam.

**Comment by electricJP** [comment]
Hello,

I think I have 2 issues in one: 
- first, after more debug it seems Home Assistant is sending 2 state_change instead of one. So this one is not on your side obviously. 
- then there is the retry issue, which I can't reproduce manually with a test flow at this time. I will try at different time of the day and let you know.

**Comment by electricJP** [comment]
My bad, latest Home Assistant solved the double state change and so I do not receive double notification even in case of retries.
