### ISSUE TITLE
Command node not functional

### ISSUE THREAD

**Issue by svwhisper** [scraton/node-red-contrib-telegrambot-home#19]
I have the switch node working OK but cannot get the command node to work.  I note the switch node has a "Chat ID", which I've populated, but the command node doesn't have that field.  Where is the Chat ID specified for the command node?

Thanks for developing this useful package.

**Comment by charliejgallo** [comment]
same here, everything else works except the Command Node.... even if the chat id and user are registered i get this message `"received unauthorized message in "(my valid Chat Id number)" from 'undefined'"`.   tried reinstalling but same mistake

**Comment by scraton** [comment]
Hi there! The command node works if you message the bot directly or in a group chat. Those are the scenarios I've been testing, at least. Perhaps you have setup some restrictions on the bot configuration under the "Chat IDs" field? You can try removing those to see if the command will start responding.

If it's still an issue, please feel free to re-open. :)

**Comment by Kimovitzh** [comment]
Anyone else have issues when you have more than one command block?
It can only handle one at a time for me.
