### ISSUE TITLE
Payload node not sending message

### ISSUE THREAD

**Issue by iptvcld** [scraton/node-red-contrib-telegrambot-home#22]
i just installed the telegram node red and currently i have a function with
msg.method = "sendMessage";
msg.payload = 
{
    message: "alert " + msg.alertsensor
};
return msg;

I then am using the payload node  and method i select set by msg.method
but nothing is sending out

Is something broken or am i missing something? I have used a debug for the function and it display msg.payload message: test123 message

**Comment by Malaga82** [comment]
your payload is not valid.
You must use:
`msg.payload =
{
text: "alert " + msg.alertsensor
};`
not `"message"`
Check https://core.telegram.org/bots/api#available-methods
