### ISSUE TITLE
Markdown is not supported?

### ISSUE THREAD

**Issue by Skaronator** [scraton/node-red-contrib-telegrambot-home#3]
Thanks for this addon! It working really well so far but unfortunately the markdown doesn't work. I tried html eg. `<b>Test</b>` and markdown language `**Test**` but it doesn't work. It'll just print the html/markdown characters.

Would be cool to support markdown: https://guides.github.com/features/mastering-markdown/

**Comment by scraton** [comment]
Hi there!

You should be able to send Markdown and HTML using the payload node. You need to specify the `parse_mode` parameter when sending a message, and currently the only way to do that would be to send a full payload.

Here's an example payload you could send:

```json
{
    "text": "Hello *World*!",
    "parse_mode": "Markdown"
}
```

Using just the notify node won't specify a parse mode, so markdown and HTML won't be available there. Unless you are thinking to add support there?

Let me know how this works out for you and if you think adding formatting options to the notify node would be a more straightforward approach. :)

**Comment by Skaronator** [comment]
Hi! Thanks for the quick response. Using payload instead of notify works now.

> Let me know how this works out for you and if you think adding formatting options to the notify node would be a more straightforward approach. :)

I'd enable Markdown by default. You can always escape chars with a backslash (`\`) and Markdown is used on all Telegram clients as well.

**Comment by scraton** [comment]
Thanks for the suggestion! I can see the temptation of wanting Markdown always on, but I think I'd prefer stick with Telegram's default API behavior which is plain text. I did, however, add an option on to the notify node to specify what format you'd like to send. That should ease the burden of having to write up a full payload.

**Comment by Skaronator** [comment]
Thats fine, thanks!
