### ISSUE TITLE
Configuration for sending from Bot to Channel 

### ISSUE THREAD

**Issue by clandestine-avocado** [scraton/node-red-contrib-telegrambot-home#32]
With a telegrambot-payload node, if I select one of my bots for the Bot field, and put the ID for the channel I want the message posted to in the ID field, the msg shows up in the channel as if it were posted from the Channel itself, rather than the bot. Is there a way to configure so bots can post into channels?

My bots are named things like Location Updates, House System Updates, etc - and I would like these bots to post into this channel, and show as being from Location Updates, House System Updates, etc.

**Comment by scraton** [comment]
Hi there! Correct me if I'm wrong (I'm not super familiar with telegram channels), but it doesn't seem like that's how they're setup to work. Channels have everything posted to them as coming from the channel itself. Whether you're a bot or regular user.

I think for what you're describing you'd just want to use a group chat. Add the various bots to the same chat, and they should show up as you'd expect. Just make sure the bot is setup as an admin within that chat in order for them to be able to post messages there.
