### ISSUE TITLE
Flows stopped due to missing Node-Types  telegrambot-config

### ISSUE THREAD

**Issue by electric-m** [scraton/node-red-contrib-telegrambot-home#36]
I installed telegrambot-home through the Palett Manager under Node-RED 2.2.0 (Docker).

There were no errors after the installation, although, wenn trying to deploy the first flow, I get the warning, that the flow has been stopped due to missing telegrambot-config node.
It's right, there is no config node, but I have no idea how to solve this.

Any help appreciated.

LOG:

_12 Feb 19:22:42 - [info] Installing module: node-red-contrib-telegrambot-home, version: 0.7.0
12 Feb 19:22:59 - [info] Installed module: node-red-contrib-telegrambot-home
Sat, 12 Feb 2022 19:23:00 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:1085:14
error: Enabling Promise cancellation failed.
       Temporary fix is to load/require this library as early as possible before using any Promises.
12 Feb 19:23:00 - [info] Added node types:
12 Feb 19:23:00 - [info]  - node-red-contrib-telegrambot-home:telegrambot-config : Error: cannot enable cancellation after promises are in use (line:2)
12 Feb 19:23:00 - [info]  - node-red-contrib-telegrambot-home:telegrambot-command
12 Feb 19:23:00 - [info]  - node-red-contrib-telegrambot-home:telegrambot-switch
12 Feb 19:23:00 - [info]  - node-red-contrib-telegrambot-home:telegrambot-notify
12 Feb 19:23:00 - [info]  - node-red-contrib-telegrambot-home:telegrambot-payload
12 Feb 19:32:09 - [info] Stopping flows
12 Feb 19:32:09 - [info] [fritzbox-callmonitor:7490] Disconnected from fritzbox
12 Feb 19:32:09 - [info] Stopped flows
12 Feb 19:32:09 - [info] Waiting for missing types to be registered:
12 Feb 19:32:09 - [info]  - telegrambot-config
12 Feb 19:34:07 - [info] Stopping flows
12 Feb 19:34:07 - [info] Stopped flows
12 Feb 19:34:07 - [info] Waiting for missing types to be registered:
12 Feb 19:34:07 - [info]  - telegrambot-config_

I found out more with the Logs, but I can't conclude, how to proceed:

https://github.com/yagop/node-telegram-bot-api/issues/319#

**Comment by scraton** [comment]
Hi there! Did you configure your bot based on the README's directions? Specifically the steps described [here](https://github.com/scraton/node-red-contrib-telegrambot-home#telegram-bot-setup). When you click to edit a node related to Telegram, you should see your bot showing up under the "Bot" dropdown. If you don't, it hasn't been configured, which would lead to this particular error.

**Comment by electric-m** [comment]
I solved the issue by now through trial and error.
In the end I need to put 

`process.env["NTBA_FIX_319"] = 1;`

in line 1 of lib/util.js

Now everything works as expected. The hint came from the log and the aforementioned link above.
Still, it seems odd to me, that nobody has encountered this before me.

**Comment by scraton** [comment]
That is strange indeed. After further review, I thought it might be due to using nodered 2.2. I haven't had a chance to upgrade myself past 1.3 yet so perhaps there's a difference due to the version of node being used. But trying out nodered 2.2 with node version 14 I don't get the same error that you describe.

Glad you were able to find a fix, though. You might also try setting `NTBA_FIX_319` as an environment variable for your docker container. That way you don't have to modify the file in case of a later update overwriting your change.

**Comment by electric-m** [comment]
I did actually try to set the ENV variable for the docker container, but that didn't work for me.

I added NTBA_FIX_319 as the variable and "true" as the value.
No clue if that is even the right thing to do.
But surely it would be good to do it that way. You got any idea on that?

**Comment by electric-m** [comment]
Never mind, it worked!

I had the util.js messed up, but now, setting the docker ENV variable is enough!
