### ISSUE TITLE
received unauthorized message in ChatID From Username

### ISSUE THREAD

**Issue by tunisiano187** [scraton/node-red-contrib-telegrambot-home#41]
Hello, I use this to send notifications to a chatgroup and that part is really great.
Thank you for that.

I'm having troubles with the receiving messages part where the debug says 
`received unauthorized message in xxxx from 'xxx'`

The sending is working so i think the config has no trouble, but what am i doing wrong?

![image](https://user-images.githubusercontent.com/6095739/177719691-a273feda-7496-424d-9f40-a031ae81b84c.png)

Thank you.

**Comment by scraton** [comment]
This error is generally shown when you get a message from a user that the bot isn't expecting. You can add the user's ID in the configuration node to allow them access.
