### ISSUE TITLE
Reply for Notification

### ISSUE THREAD

**Issue by fabiojrsantos** [scraton/node-red-contrib-telegrambot-home#43]
Hello guys, I have an instance of Home Assistant installed and I use NodeRED for automations, using this palette, when I use the switch, I can't respond by notification, only by text inside the window. 
Would there be any way to respond by notification?
Thanks.

**Comment by scraton** [comment]
I don't believe Telegram supports responding to the notification directly, I'm afraid. If someone is able to find an API that allows for that, I'd be happy to accept a PR.
