### ISSUE TITLE
received callback was unauthorized

### ISSUE THREAD

**Issue by claudioita** [scraton/node-red-contrib-telegrambot-home#5]
Hi I am using a TELEGRAM SWITCH with multiple answers, the message is correctly sent to the phone with telegram on. When in the phone I click one of the answers, then in node-red I see this:

"received callback in MY_CHAT_ID from 'claudioita' was unauthorized"

Must be sometrhing I did not do, but I don't know what ...

**Comment by scraton** [comment]
Hi there!

On your configuration node (where you specified your Telegram API token), did you fill anything in the "Users" field? If you did, you need to ensure the user you're using, claudioita in this case, is included in that list.

Alternatively, you can leave it blank to allow any user to interact with the bot.

Let me know if that helps solve your problem! :)

EDIT: I believe this may be the same issue as this one: https://github.com/scraton/node-red-contrib-telegrambot-home/issues/1

**Comment by claudioita** [comment]
Ehhh, yes that was it. It was a different name. Besides I have no idea in which part of the coinfiguration does this name (claudioita) come freom).

Problem solved. Thanks!

**Comment by scraton** [comment]
That should be your Telegram username. But I’m glad to hear you got it working! :)
