### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by filoor** [scraton/node-red-contrib-telegrambot-home#7]
Hi,

Im facing the next problem!
Can you please help me

28 Jun 09:26:20 - [info] Node-RED version: v0.18.4
28 Jun 09:26:20 - [info] Node.js  version: v8.10.0
28 Jun 09:26:20 - [info] Linux 4.9.49-moby x64 LE
28 Jun 09:26:20 - [info] Loading palette nodes
28 Jun 09:26:20 - [info] RedBot version: 0.13.3 (node-red-contrib-chatbot)
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30
28 Jun 09:26:22 - [info] Dashboard version 2.8.2 started at /ui
28 Jun 09:26:22 - [warn] ------------------------------------------------------
28 Jun 09:26:22 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
28 Jun 09:26:22 - [warn] ------------------------------------------------------
28 Jun 09:26:22 - [info] Settings file  : /usr/src/app/settings.js
28 Jun 09:26:22 - [info] User directory : /usr/src/app
28 Jun 09:26:22 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
28 Jun 09:26:22 - [info] Flows file     : /usr/src/app/flow.json
28 Jun 09:26:22 - [info] Server now running at http://127.0.0.1:1880/
28 Jun 09:26:22 - [info] Starting flows
28 Jun 09:26:22 - [info] Started flows
28 Jun 09:29:01 - [warn] [telegrambot-config:61ae51ef.5faa3] EFATAL: Error: read ECONNRESET
28 Jun 09:29:01 - [warn] [telegrambot-config:61ae51ef.5faa3] Network connection may be down. Trying again.

**Comment by scraton** [comment]
Hi filoor,

That error would seem to indicate some sort of connection problem between your computer running node red and Telegram. Can you verify that whatever is running node red, be it a server or docker container, can connect to `https://api.telegram.org` successfully?

**Comment by scraton** [comment]
I'm going to close this since I haven't heard back in a while. Let me know if you're still experiencing the issue and I'd be happy to reopen and discuss it further. :)
